server:
  port: 9707

spring:
  application:
    name: iotonix-tenant-profile

  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  datasource:
    driverClassName: org.postgresql.Driver
    #    url: jdbc:postgresql://10.0.249.16:5432/tenant_management
    #    username: admin_iox
    #    password: dtSDD@a1t2022
    url: jdbc:postgresql://localhost:5432/tenant_management
    username: tenant_admin
    password: TenatP@ssw0rd1!
    hikari:
      minimumIdle: 1
      maximumPoolSize: 5
      idleTimeout: 22000
      connectionTimeout: 10000
      leakDetectionThreshold: 10000


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://10.0.253.238:8761/eureka/
    enabled: false

management:
  endpoint:
    restart:
      enabled: true
  health:
    ldap:
      enabled: false
  security:
    enabled: false

  endpoints:
    web:
      exposure:
        include: restart,health
